package js.aws.rds;

typedef CreateDBClusterInput = {
    @:optional var EngineVersion : String;
    @:optional var EnableCloudwatchLogsExports : _ShapeS1n;
    @:optional var PreSignedUrl : String;
    @:optional var VpcSecurityGroupIds : _ShapeS1l;
    @:optional var DBSubnetGroupName : String;
    @:optional var GlobalClusterIdentifier : String;
    @:optional var DatabaseName : String;
    @:optional var EngineMode : String;
    @:optional var PreferredBackupWindow : String;
    @:optional var KmsKeyId : String;
    @:optional var CharacterSetName : String;
    @:optional var DeletionProtection : Bool;
    @:optional var ScalingConfiguration : _ShapeS1o;
    @:optional var BackupRetentionPeriod : Int;
    @:optional var ReplicationSourceIdentifier : String;
    @:optional var BacktrackWindow : Int;
    @:optional var EnableIAMDatabaseAuthentication : Bool;
    var DBClusterIdentifier : String;
    @:optional var PreferredMaintenanceWindow : String;
    @:optional var DBClusterParameterGroupName : String;
    @:optional var MasterUserPassword : String;
    @:optional var AvailabilityZones : _ShapeSy;
    var Engine : String;
    @:optional var MasterUsername : String;
    @:optional var OptionGroupName : String;
    @:optional var Port : Int;
    @:optional var Tags : _ShapeSa;
    @:optional var StorageEncrypted : Bool;
    @:optional var SourceRegion : String;
};
