package js.aws.rds;

typedef CreateDBInstanceReadReplicaInput = {
    @:optional var DBInstanceClass : String;
    var SourceDBInstanceIdentifier : String;
    @:optional var EnableCloudwatchLogsExports : _ShapeS1n;
    @:optional var MultiAZ : Bool;
    var DBInstanceIdentifier : String;
    @:optional var EnablePerformanceInsights : Bool;
    @:optional var PreSignedUrl : String;
    @:optional var AvailabilityZone : String;
    @:optional var MonitoringRoleArn : String;
    @:optional var VpcSecurityGroupIds : _ShapeS1l;
    @:optional var DBSubnetGroupName : String;
    @:optional var CopyTagsToSnapshot : Bool;
    @:optional var UseDefaultProcessorFeatures : Bool;
    @:optional var KmsKeyId : String;
    @:optional var AutoMinorVersionUpgrade : Bool;
    @:optional var DeletionProtection : Bool;
    @:optional var PerformanceInsightsKMSKeyId : String;
    @:optional var PubliclyAccessible : Bool;
    @:optional var PerformanceInsightsRetentionPeriod : Int;
    @:optional var MonitoringInterval : Int;
    @:optional var EnableIAMDatabaseAuthentication : Bool;
    @:optional var StorageType : String;
    @:optional var ProcessorFeatures : _ShapeS17;
    @:optional var Iops : Int;
    @:optional var OptionGroupName : String;
    @:optional var Port : Int;
    @:optional var Tags : _ShapeSa;
    @:optional var SourceRegion : String;
};
