package js.aws.rds;

typedef RestoreDBInstanceFromS3Input = {
    var DBInstanceClass : String;
    @:optional var EngineVersion : String;
    @:optional var EnableCloudwatchLogsExports : _ShapeS1n;
    @:optional var MultiAZ : Bool;
    var DBInstanceIdentifier : String;
    @:optional var EnablePerformanceInsights : Bool;
    @:optional var AvailabilityZone : String;
    @:optional var MonitoringRoleArn : String;
    @:optional var VpcSecurityGroupIds : _ShapeS1l;
    @:optional var DBSecurityGroups : _ShapeS27;
    @:optional var DBSubnetGroupName : String;
    @:optional var AllocatedStorage : Int;
    @:optional var CopyTagsToSnapshot : Bool;
    var SourceEngineVersion : String;
    var S3BucketName : String;
    @:optional var PreferredBackupWindow : String;
    @:optional var UseDefaultProcessorFeatures : Bool;
    @:optional var KmsKeyId : String;
    @:optional var DBName : String;
    @:optional var AutoMinorVersionUpgrade : Bool;
    @:optional var DeletionProtection : Bool;
    @:optional var BackupRetentionPeriod : Int;
    @:optional var PerformanceInsightsKMSKeyId : String;
    @:optional var PubliclyAccessible : Bool;
    @:optional var PerformanceInsightsRetentionPeriod : Int;
    @:optional var MonitoringInterval : Int;
    @:optional var EnableIAMDatabaseAuthentication : Bool;
    @:optional var PreferredMaintenanceWindow : String;
    @:optional var StorageType : String;
    @:optional var MasterUserPassword : String;
    @:optional var DBParameterGroupName : String;
    @:optional var ProcessorFeatures : _ShapeS17;
    @:optional var Iops : Int;
    var Engine : String;
    @:optional var MasterUsername : String;
    @:optional var OptionGroupName : String;
    var S3IngestionRoleArn : String;
    @:optional var Port : Int;
    @:optional var S3Prefix : String;
    @:optional var Tags : _ShapeSa;
    @:optional var LicenseModel : String;
    var SourceEngine : String;
    @:optional var StorageEncrypted : Bool;
};
