package js.aws.rds;

typedef RestoreDBInstanceToPointInTimeInput = {
    @:optional var DBInstanceClass : String;
    @:optional var SourceDBInstanceIdentifier : String;
    @:optional var EnableCloudwatchLogsExports : _ShapeS1n;
    @:optional var MultiAZ : Bool;
    @:optional var AvailabilityZone : String;
    @:optional var VpcSecurityGroupIds : _ShapeS1l;
    @:optional var RestoreTime : Float;
    @:optional var DBSubnetGroupName : String;
    @:optional var CopyTagsToSnapshot : Bool;
    @:optional var SourceDbiResourceId : String;
    @:optional var UseDefaultProcessorFeatures : Bool;
    @:optional var Domain : String;
    @:optional var DBName : String;
    @:optional var AutoMinorVersionUpgrade : Bool;
    @:optional var UseLatestRestorableTime : Bool;
    @:optional var DeletionProtection : Bool;
    var TargetDBInstanceIdentifier : String;
    @:optional var PubliclyAccessible : Bool;
    @:optional var TdeCredentialArn : String;
    @:optional var TdeCredentialPassword : String;
    @:optional var EnableIAMDatabaseAuthentication : Bool;
    @:optional var DomainIAMRoleName : String;
    @:optional var StorageType : String;
    @:optional var DBParameterGroupName : String;
    @:optional var ProcessorFeatures : _ShapeS17;
    @:optional var Iops : Int;
    @:optional var Engine : String;
    @:optional var OptionGroupName : String;
    @:optional var Port : Int;
    @:optional var Tags : _ShapeSa;
    @:optional var LicenseModel : String;
};
