package js.aws.cognitoidentityserviceprovider;

typedef _ShapeS5l = {
    @:optional var CreationDate : Float;
    @:optional var EmailVerificationSubject : String;
    @:optional var AutoVerifiedAttributes : _ShapeS4v;
    @:optional var Policies : _ShapeS4r;
    @:optional var SmsConfigurationFailure : String;
    @:optional var UsernameAttributes : _ShapeS4z;
    @:optional var Domain : String;
    @:optional var LastModifiedDate : Float;
    @:optional var AliasAttributes : _ShapeS4x;
    @:optional var EmailConfiguration : _ShapeS5a;
    @:optional var CustomDomain : String;
    @:optional var SmsAuthenticationMessage : String;
    @:optional var SmsConfiguration : _ShapeS5c;
    @:optional var Id : String;
    @:optional var Arn : String;
    @:optional var UserPoolAddOns : _ShapeS5i;
    @:optional var EstimatedNumberOfUsers : Int;
    @:optional var LambdaConfig : _ShapeS4u;
    @:optional var SmsVerificationMessage : String;
    @:optional var MfaConfiguration : String;
    @:optional var VerificationMessageTemplate : _ShapeS54;
    @:optional var AdminCreateUserConfig : _ShapeS5e;
    @:optional var DeviceConfiguration : _ShapeS59;
    @:optional var EmailConfigurationFailure : String;
    @:optional var SchemaAttributes : _ShapeS5h;
    @:optional var Name : String;
    @:optional var UserPoolTags : _ShapeS5d;
    @:optional var EmailVerificationMessage : String;
    @:optional var Status : String;
};
