package js.aws.redshift;

typedef CreateClusterInput = {
    @:optional var ClusterSubnetGroupName : String;
    @:optional var ElasticIp : String;
    @:optional var AvailabilityZone : String;
    @:optional var NumberOfNodes : Int;
    @:optional var VpcSecurityGroupIds : _ShapeS1e;
    var NodeType : String;
    @:optional var HsmClientCertificateIdentifier : String;
    @:optional var EnhancedVpcRouting : Bool;
    @:optional var HsmConfigurationIdentifier : String;
    @:optional var KmsKeyId : String;
    @:optional var DBName : String;
    @:optional var ManualSnapshotRetentionPeriod : Int;
    @:optional var MaintenanceTrackName : String;
    @:optional var ClusterVersion : String;
    @:optional var ClusterSecurityGroups : _ShapeS1d;
    @:optional var ClusterType : String;
    var ClusterIdentifier : String;
    @:optional var Encrypted : Bool;
    @:optional var PubliclyAccessible : Bool;
    @:optional var AllowVersionUpgrade : Bool;
    @:optional var SnapshotScheduleIdentifier : String;
    @:optional var ClusterParameterGroupName : String;
    @:optional var PreferredMaintenanceWindow : String;
    @:optional var IamRoles : _ShapeS1g;
    @:optional var AutomatedSnapshotRetentionPeriod : Int;
    var MasterUserPassword : String;
    var MasterUsername : String;
    @:optional var AdditionalInfo : String;
    @:optional var Port : Int;
    @:optional var Tags : _ShapeSg;
};
