package js.aws.mediaconvert;

typedef _ShapeS82 = {
    @:optional var TimecodeInsertion : String;
    @:optional var AfdSignaling : String;
    @:optional var DropFrameTimecode : String;
    @:optional var Width : Int;
    @:optional var RespondToAfd : String;
    @:optional var CodecSettings : {
        @:optional var FrameCaptureSettings : {
            @:optional var FramerateDenominator : Int;
            @:optional var Quality : Int;
            @:optional var MaxCaptures : Int;
            @:optional var FramerateNumerator : Int;
        };
        @:optional var H265Settings : {
            @:optional var TemporalAdaptiveQuantization : String;
            @:optional var FramerateConversionAlgorithm : String;
            @:optional var Telecine : String;
            @:optional var Bitrate : Int;
            @:optional var FlickerAdaptiveQuantization : String;
            @:optional var CodecProfile : String;
            @:optional var GopBReference : String;
            @:optional var HrdBufferSize : Int;
            @:optional var GopClosedCadence : Int;
            @:optional var ParDenominator : Int;
            @:optional var QualityTuningLevel : String;
            @:optional var MaxBitrate : Int;
            @:optional var SlowPal : String;
            @:optional var ParControl : String;
            @:optional var ParNumerator : Int;
            @:optional var MinIInterval : Int;
            @:optional var NumberBFramesBetweenReferenceFrames : Int;
            @:optional var AdaptiveQuantization : String;
            @:optional var SampleAdaptiveOffsetFilterMode : String;
            @:optional var RateControlMode : String;
            @:optional var AlternateTransferFunctionSei : String;
            @:optional var HrdBufferInitialFillPercentage : Int;
            @:optional var DynamicSubGop : String;
            @:optional var FramerateControl : String;
            @:optional var GopSizeUnits : String;
            @:optional var FramerateDenominator : Int;
            @:optional var NumberReferenceFrames : Int;
            @:optional var SceneChangeDetect : String;
            @:optional var WriteMp4PackagingType : String;
            @:optional var GopSize : Float;
            @:optional var Tiles : String;
            @:optional var Slices : Int;
            @:optional var CodecLevel : String;
            @:optional var QvbrSettings : {
                @:optional var QvbrQualityLevel : Int;
                @:optional var MaxAverageBitrate : Int;
            };
            @:optional var InterlaceMode : String;
            @:optional var FramerateNumerator : Int;
            @:optional var SpatialAdaptiveQuantization : String;
            @:optional var TemporalIds : String;
            @:optional var UnregisteredSeiTimecode : String;
        };
        @:optional var ProresSettings : {
            @:optional var FramerateConversionAlgorithm : String;
            @:optional var Telecine : String;
            @:optional var CodecProfile : String;
            @:optional var ParDenominator : Int;
            @:optional var SlowPal : String;
            @:optional var ParControl : String;
            @:optional var ParNumerator : Int;
            @:optional var FramerateControl : String;
            @:optional var FramerateDenominator : Int;
            @:optional var InterlaceMode : String;
            @:optional var FramerateNumerator : Int;
        };
        @:optional var Codec : String;
        @:optional var H264Settings : {
            @:optional var TemporalAdaptiveQuantization : String;
            @:optional var FramerateConversionAlgorithm : String;
            @:optional var Telecine : String;
            @:optional var Bitrate : Int;
            @:optional var FlickerAdaptiveQuantization : String;
            @:optional var CodecProfile : String;
            @:optional var GopBReference : String;
            @:optional var HrdBufferSize : Int;
            @:optional var GopClosedCadence : Int;
            @:optional var ParDenominator : Int;
            @:optional var RepeatPps : String;
            @:optional var QualityTuningLevel : String;
            @:optional var MaxBitrate : Int;
            @:optional var SlowPal : String;
            @:optional var ParControl : String;
            @:optional var ParNumerator : Int;
            @:optional var MinIInterval : Int;
            @:optional var NumberBFramesBetweenReferenceFrames : Int;
            @:optional var Softness : Int;
            @:optional var EntropyEncoding : String;
            @:optional var FieldEncoding : String;
            @:optional var AdaptiveQuantization : String;
            @:optional var RateControlMode : String;
            @:optional var HrdBufferInitialFillPercentage : Int;
            @:optional var DynamicSubGop : String;
            @:optional var FramerateControl : String;
            @:optional var GopSizeUnits : String;
            @:optional var FramerateDenominator : Int;
            @:optional var NumberReferenceFrames : Int;
            @:optional var SceneChangeDetect : String;
            @:optional var GopSize : Float;
            @:optional var Syntax : String;
            @:optional var Slices : Int;
            @:optional var CodecLevel : String;
            @:optional var QvbrSettings : {
                @:optional var QvbrQualityLevel : Int;
                @:optional var MaxAverageBitrate : Int;
            };
            @:optional var InterlaceMode : String;
            @:optional var FramerateNumerator : Int;
            @:optional var SpatialAdaptiveQuantization : String;
            @:optional var UnregisteredSeiTimecode : String;
        };
        @:optional var Mpeg2Settings : {
            @:optional var TemporalAdaptiveQuantization : String;
            @:optional var FramerateConversionAlgorithm : String;
            @:optional var Telecine : String;
            @:optional var Bitrate : Int;
            @:optional var CodecProfile : String;
            @:optional var HrdBufferSize : Int;
            @:optional var GopClosedCadence : Int;
            @:optional var ParDenominator : Int;
            @:optional var QualityTuningLevel : String;
            @:optional var MaxBitrate : Int;
            @:optional var SlowPal : String;
            @:optional var ParControl : String;
            @:optional var ParNumerator : Int;
            @:optional var MinIInterval : Int;
            @:optional var NumberBFramesBetweenReferenceFrames : Int;
            @:optional var Softness : Int;
            @:optional var AdaptiveQuantization : String;
            @:optional var RateControlMode : String;
            @:optional var HrdBufferInitialFillPercentage : Int;
            @:optional var DynamicSubGop : String;
            @:optional var FramerateControl : String;
            @:optional var GopSizeUnits : String;
            @:optional var FramerateDenominator : Int;
            @:optional var SceneChangeDetect : String;
            @:optional var GopSize : Float;
            @:optional var Syntax : String;
            @:optional var CodecLevel : String;
            @:optional var InterlaceMode : String;
            @:optional var FramerateNumerator : Int;
            @:optional var SpatialAdaptiveQuantization : String;
            @:optional var IntraDcPrecision : String;
        };
    };
    @:optional var ScalingBehavior : String;
    @:optional var ColorMetadata : String;
    @:optional var FixedAfd : Int;
    @:optional var Position : _ShapeSaw;
    @:optional var VideoPreprocessors : {
        @:optional var ImageInserter : _ShapeS1q;
        @:optional var TimecodeBurnin : {
            @:optional var Prefix : String;
            @:optional var Position : String;
            @:optional var FontSize : Int;
        };
        @:optional var ColorCorrector : {
            @:optional var ColorSpaceConversion : String;
            @:optional var Brightness : Int;
            @:optional var Saturation : Int;
            @:optional var Hue : Int;
            @:optional var Contrast : Int;
            @:optional var Hdr10Metadata : _ShapeS26;
        };
        @:optional var Deinterlacer : {
            @:optional var Control : String;
            @:optional var Mode : String;
            @:optional var Algorithm : String;
        };
        @:optional var NoiseReducer : {
            @:optional var SpatialFilterSettings : {
                @:optional var PostFilterSharpenStrength : Int;
                @:optional var Strength : Int;
                @:optional var Speed : Int;
            };
            @:optional var FilterSettings : {
                @:optional var Strength : Int;
            };
            @:optional var Filter : String;
        };
    };
    @:optional var AntiAlias : String;
    @:optional var Crop : _ShapeSaw;
    @:optional var Height : Int;
    @:optional var Sharpness : Int;
};
